/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    maven {
      url = uri("https://artifactory.endhealth.co.uk/repository/maven-releases")
    }
    maven {
      url = uri("https://artifactory.endhealth.co.uk/repository/maven-snapshots")
    }
    mavenLocal()
  }

  resolutionStrategy {
    eachPlugin {
      if (requested.id.id == "cz.habarta.typescript-generator") {
        useModule("cz.habarta.typescript-generator:typescript-generator-gradle-plugin:${requested.version ?: "+"}")
      }
    }
  }
  plugins {
    kotlin("jvm") version "2.2.20"
  }
}
plugins {
  id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "VueLibrary"

include(":Library")
