// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class COMPONENT {

  public static readonly DOMAIN = "http://endhealth.info/im#"
  public static readonly TAB_LAYOUT = NAMESPACE.IM_COMPONENT + "TabLayout"
  public static readonly TEXT_DISPLAY = NAMESPACE.IM_COMPONENT + "textDisplay"
  public static readonly TEXT_INPUT = NAMESPACE.IM_COMPONENT + "textInput"
  public static readonly HTML_INPUT = NAMESPACE.IM_COMPONENT + "htmlInput"
  public static readonly ENTITY_MULTI_SEARCH = NAMESPACE.IM_COMPONENT + "entityMultiSearch"
  public static readonly ENTITY_SEARCH = NAMESPACE.IM_COMPONENT + "entitySearch"
  public static readonly ENTITY_COMBOBOX = NAMESPACE.IM_COMPONENT + "entityComboBox"
  public static readonly ENTITY_DROPDOWN = NAMESPACE.IM_COMPONENT + "entityDropdown"
  public static readonly ARRAY_BUILDER = NAMESPACE.IM_COMPONENT + "arrayBuilder"
  public static readonly ENTITY_AUTO_COMPLETE = NAMESPACE.IM_COMPONENT + "entityAutoComplete"
  public static readonly MEMBERS_BUILDER = NAMESPACE.IM_COMPONENT + "membersBuilder"
  public static readonly COMPONENT_GROUP = NAMESPACE.IM_COMPONENT + "componentGroup"
  public static readonly PROPERTY_BUILDER = NAMESPACE.IM_COMPONENT + "propertyBuilder"
  public static readonly SET_DEFINITION_BUILDER = NAMESPACE.IM_COMPONENT + "SetDefinitionBuilder"
  public static readonly QUERY_DEFINITION_BUILDER = NAMESPACE.IM_COMPONENT + "QueryDefinitionBuilder"
  public static readonly TOGGLEABLE = NAMESPACE.IM_COMPONENT + "ToggleableComponent"
  public static readonly HORIZONTAL_LAYOUT = NAMESPACE.IM_COMPONENT + "HorizontalLayout"
  public static readonly VERTICAL_LAYOUT = NAMESPACE.IM_COMPONENT + "VerticalLayout"
  public static readonly DROPDOWN_TEXT_INPUT_CONCATENATOR = NAMESPACE.IM_COMPONENT + "dropdownTextInputConcatenator"
  public static readonly ROLE_GROUP_BUILDER = NAMESPACE.IM_COMPONENT + "roleGroupBuilder"
  public static readonly TERM_CODE_EDITOR = NAMESPACE.IM_COMPONENT + "termCodeEditor"
  public static readonly TEXT_DROPDOWN = NAMESPACE.IM_COMPONENT + "textDropdown"
  public static readonly ENTITY_DISPLAY = NAMESPACE.IM_COMPONENT + "entityDisplay"
  public static readonly IRI_BUILDER = NAMESPACE.IM_COMPONENT + "iriBuilder"
  public static readonly AUTOCOMPLETE_SEARCH_BAR_WRAPPER = NAMESPACE.IM_COMPONENT + "autocompleteSearchBarWrapper"
  public static readonly SUBSET_BUILDER = NAMESPACE.IM_COMPONENT + "subsetBuilder"
  public static readonly CHECKBOX_DISPLAY = NAMESPACE.IM_COMPONENT + "checkboxDisplay"
}
