// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class EDITOR {

  public static readonly DOMAIN = "http://endhealth.info/im#"
  public static readonly CONCEPT_SHAPE = NAMESPACE.IM_EDITOR + "ConceptShape"
  public static readonly CONCEPT_SET_SHAPE = NAMESPACE.IM_EDITOR + "ConceptSetShape"
  public static readonly VALUE_SET_SHAPE = NAMESPACE.IM_EDITOR + "ValueSetShape"
  public static readonly FOLDER_SHAPE = NAMESPACE.IM_EDITOR + "FolderShape"
  public static readonly DATA_MODEL_SHAPE = NAMESPACE.IM_EDITOR + "DataModelShape"
  public static readonly COHORT_QUERY_SHAPE = NAMESPACE.IM_EDITOR + "CohortQueryShape"
  public static readonly PROPERTY_SHAPE = NAMESPACE.IM_EDITOR + "PropertyShape"
  public static readonly INDICATOR_SHAPE = NAMESPACE.IM_EDITOR + "IndicatorShape"
}
