// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class IM_FUNCTION {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly SNOMED_CONCEPT_GENERATOR = NAMESPACE.FUNCTION + "SnomedConceptGenerator"
  public static readonly LOCAL_NAME_RETRIEVER = NAMESPACE.FUNCTION + "LocalNameRetriever"
  public static readonly GET_ADDITIONAL_ALLOWABLE_TYPES = NAMESPACE.FUNCTION + "GetAdditionalAllowableTypes"
  public static readonly GET_LOGIC_OPTIONS = NAMESPACE.FUNCTION + "GetLogicOptions"
  public static readonly GET_SET_EDITOR_IRI_SCHEMES = NAMESPACE.FUNCTION + "GetSetEditorIriSchemes"
  public static readonly IM1_SCHEME_OPTIONS = NAMESPACE.FUNCTION + "IM1SchemeOptions"
  public static readonly SCHEME_FROM_IRI = NAMESPACE.FUNCTION + "SchemeFromIri"
  public static readonly GET_USER_EDITABLE_SCHEMES = NAMESPACE.FUNCTION + "GetUserEditableSchemes"
  public static readonly IS_TYPE = NAMESPACE.FUNCTION + "IsType"
  public static readonly ALLOWABLE_PROPERTIES = NAMESPACE.FUNCTION + "AllowableProperties"
  public static readonly ALLOWABLE_RANGES = NAMESPACE.FUNCTION + "AllowableRanges"
  public static readonly ALLOWABLE_PROPERTY_VALUES = NAMESPACE.FUNCTION + "AllowablePropertyValues"
}
