// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class OWL {

  public static readonly PREFIX = "owl"
  public static readonly THING = NAMESPACE.OWL + "Thing"
  public static readonly CLASS = NAMESPACE.OWL + "Class"
  public static readonly EQUIVALENT_CLASS = NAMESPACE.OWL + "equivalentClass"
  public static readonly INTERSECTION_OF = NAMESPACE.OWL + "intersectionOf"
  public static readonly UNION_OF = NAMESPACE.OWL + "unionOf"
  public static readonly RESTRICTION = NAMESPACE.OWL + "Restriction"
  public static readonly ON_PROPERTY = NAMESPACE.OWL + "onProperty"
  public static readonly ON_CLASS = NAMESPACE.OWL + "onClass"
  public static readonly SOME_VALUES_FROM = NAMESPACE.OWL + "someValuesFrom"
  public static readonly ALL_VALUES_FROM = NAMESPACE.OWL + "allValuesFrom"
  public static readonly OBJECT_PROPERTY = NAMESPACE.OWL + "ObjectProperty"
  public static readonly DATATYPE_PROPERTY = NAMESPACE.OWL + "DatatypeProperty"
  public static readonly ANNOTATION_PROPERTY = NAMESPACE.OWL + "AnnotationProperty"
  public static readonly INVERSE_OF = NAMESPACE.OWL + "inverseOf"
  public static readonly INVERSE_OBJECT_PROPERTY = NAMESPACE.OWL + "inverseOf"
  public static readonly PROPERTY_CHAIN = NAMESPACE.OWL + "propertyChainAxiom"
  public static readonly TRANSITIVE = NAMESPACE.OWL + "TransitiveProperty"
  public static readonly FUNCTIONAL = NAMESPACE.OWL + "FunctionalProperty"
  public static readonly SYMMETRIC = NAMESPACE.OWL + "SymmetricProperty"
  public static readonly REFLEXIVE = NAMESPACE.OWL + "ReflexiveProperty"
  public static readonly ON_DATATYPE = NAMESPACE.OWL + "onDatatype"
  public static readonly WITH_RESTRICTIONS = NAMESPACE.OWL + "withRestrictions"
  public static readonly MAX_CARDINALITY = NAMESPACE.OWL + "maxCardinality"
  public static readonly MIN_CARDINALITY = NAMESPACE.OWL + "minCardinality"
  public static readonly ON_DATA_RANGE = NAMESPACE.OWL + "onDataRange"
  public static readonly HAS_VALUE = NAMESPACE.OWL + "hasValue"
  public static readonly COMPLEMENT_OF = NAMESPACE.OWL + "complementOf"
  public static readonly ONE_OF = NAMESPACE.OWL + "oneOf"
  public static readonly NAMED_INDIVIDUAL = NAMESPACE.OWL + "NamedIndividual"
}
