// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class QUERY {

  public static readonly DOMAIN = "http://endhealth.info/im#"
  public static readonly IS_ALLOWABLE_RANGE = NAMESPACE.IM_QUERY + "IsAllowableRange"
  public static readonly ALLOWABLE_RANGE_SUGGESTIONS = NAMESPACE.IM_QUERY + "AllowableRangeSuggestions"
  public static readonly GET_SUBCLASSES = NAMESPACE.IM_QUERY + "GetSubClasses"
  public static readonly GET_DESCENDANTS = NAMESPACE.IM_QUERY + "GetDescendants"
  public static readonly IS_VALID_DESCENDANT = NAMESPACE.IM_QUERY + "IsValidDescendant"
  public static readonly GET_ANCESTORS = NAMESPACE.IM_QUERY + "GetAncestors"
  public static readonly SEARCH_CONTAINED_IN = NAMESPACE.IM_QUERY + "SearchContainedIn"
  public static readonly ALLOWABLE_CHILD_TYPES = NAMESPACE.IM_QUERY + "AllowableChildTypes"
  public static readonly PROPERTY_RANGE = NAMESPACE.IM_QUERY + "PropertyRange"
  public static readonly OBJECT_PROPERTY_RANGE_SUGGESTIONS = NAMESPACE.IM_QUERY + "ObjectPropertyRangeSuggestions"
  public static readonly DATA_PROPERTY_RANGE_SUGGESTIONS = NAMESPACE.IM_QUERY + "DataPropertyRangeSuggestions"
  public static readonly ALLOWABLE_PROPERTIES = NAMESPACE.IM_QUERY + "AllowableProperties"
  public static readonly ALLOWABLE_PROPERTY_ANCESTORS = NAMESPACE.IM_QUERY + "AllowablePropertyAncestors"
  public static readonly IS_VALID_PROPERTY = NAMESPACE.IM_QUERY + "IsValidProperty"
  public static readonly ENTITY_FILTER = NAMESPACE.IM_QUERY + "EntityFilter"
  public static readonly SEARCH_ENTITIES = NAMESPACE.IM_QUERY + "SearchEntities"
  public static readonly SEARCH_FOLDERS = NAMESPACE.IM_QUERY + "SearchFolders"
  public static readonly SEARCH_ALLOWABLE_CONTAINED_IN = NAMESPACE.IM_QUERY + "SearchAllowableContainedIn"
  public static readonly SEARCH_MAIN_TYPES = NAMESPACE.IM_QUERY + "SearchmainTypes"
  public static readonly DM_PROPERTY = NAMESPACE.IM_QUERY + "DataModelPropertyByShape"
  public static readonly SEARCH_ALLOWABLE_SUBCLASS = NAMESPACE.IM_QUERY + "SearchAllowableSubclass"
  public static readonly GET_VALUES_FROM_PROPERTY_RANGE = NAMESPACE.IM_QUERY + "GetValuesFromPropertyRange"
  public static readonly GET_SUBSETS = NAMESPACE.IM_QUERY + "GetSubsets"
}
