// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class RDF {

  public static readonly PREFIX = "rdf"
  public static readonly TYPE = NAMESPACE.RDF + "type"
  public static readonly PROPERTY = NAMESPACE.RDF + "Property"
  public static readonly LIST = NAMESPACE.RDF + "List"
  public static readonly PREDICATE = NAMESPACE.RDF + "predicate"
  public static readonly SUBJECT = NAMESPACE.RDF + "subject"
  public static readonly OBJECT = NAMESPACE.RDF + "object"
}
