// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class RDFS {

  public static readonly PREFIX = "rdfs"
  public static readonly LABEL = NAMESPACE.RDFS + "label"
  public static readonly COMMENT = NAMESPACE.RDFS + "comment"
  public static readonly SUBCLASS_OF = NAMESPACE.RDFS + "subClassOf"
  public static readonly SUB_PROPERTY_OF = NAMESPACE.RDFS + "subPropertyOf"
  public static readonly DOMAIN = NAMESPACE.RDFS + "domain"
  public static readonly RANGE = NAMESPACE.RDFS + "range"
  public static readonly RESOURCE = NAMESPACE.RDFS + "Resource"
  public static readonly CLASS = NAMESPACE.RDFS + "Class"
  public static readonly DATATYPE = NAMESPACE.RDFS + "Datatype"
  public static readonly IS_DEFINED_BY = NAMESPACE.RDFS + "isDefinedBy"
}
