// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class SNOMED {

  public static readonly DOMAIN = "http://snomed.info/"
  public static readonly PREFIX = "sn"
  public static readonly ATTRIBUTE = NAMESPACE.SNOMED + "246061005"
  public static readonly ANY = NAMESPACE.SNOMED + "*"
}
