// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";
import {IM} from "@/vocabulary/IM";

export class TRANSFORM_FUNCTION {

  public static readonly CONCATENATE = NAMESPACE.IM + "Concatenate"
  public static readonly STRING_JOIN = NAMESPACE.IM + "StringJoin"
  public static readonly SNOMED_CODE_CONCEPT_MAP = NAMESPACE.IM + "SchemedCodeConceptMap"
}
