// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class USER {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly PREFIX = "usr"
  public static readonly USER_PRESET = NAMESPACE.USER + "UserPreset"
  public static readonly USER_PRIMARY_COLOR = NAMESPACE.USER + "UserPrimaryColor"
  public static readonly USER_SURFACE_COLOR = NAMESPACE.USER + "UserSurfaceColor"
  public static readonly USER_DARK_MODE = NAMESPACE.USER + "UserDarkMode"
  public static readonly USER_FONT_SIZE = NAMESPACE.USER + "UserFontSize"
  public static readonly USER_MRU = NAMESPACE.USER + "UserMRU"
  public static readonly USER_FAVOURITES = NAMESPACE.USER + "UserFavourites"
  public static readonly ORGANISATIONS = NAMESPACE.USER + "Organisations"
  public static readonly GRAPHS = NAMESPACE.USER + "Graphs"
}
