// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class VALIDATION {

  public static readonly DOMAIN = "http://endhealth.info/im#"
  public static readonly IS_DEFINITION = NAMESPACE.IM_VALIDATION + "isDefinition"
  public static readonly HAS_PARENT = NAMESPACE.IM_VALIDATION + "hasParent"
  public static readonly IS_IRI = NAMESPACE.IM_VALIDATION + "isIri"
  public static readonly IS_TERMCODE = NAMESPACE.IM_VALIDATION + "isTermcode"
  public static readonly IS_PROPERTY = NAMESPACE.IM_VALIDATION + "isProperty"
  public static readonly IS_SCHEME = NAMESPACE.IM_VALIDATION + "isScheme"
  public static readonly IS_STATUS = NAMESPACE.IM_VALIDATION + "isStatus"
  public static readonly IS_ROLE_GROUP = NAMESPACE.IM_VALIDATION + "isRoleGroup"
}
