// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class WORKFLOW {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly BUG_REPORT = NAMESPACE.WORKFLOW + "bugReport"
  public static readonly DATE_CREATED = NAMESPACE.WORKFLOW + "dateCreated"
  public static readonly CREATED_BY = NAMESPACE.WORKFLOW + "createdBy"
  public static readonly ASSIGNED_TO = NAMESPACE.WORKFLOW + "assignedTo"
  public static readonly STATE = NAMESPACE.WORKFLOW + "state"
  public static readonly HOST_URL = NAMESPACE.WORKFLOW + "hostUrl"
  public static readonly RELATED_PRODUCT = NAMESPACE.WORKFLOW + "relatedProduct"
  public static readonly RELATED_MODULE = NAMESPACE.WORKFLOW + "relatedModule"
  public static readonly OPERATING_SYSTEM = NAMESPACE.WORKFLOW + "operatingSystem"
  public static readonly OPERATING_SYSTEM_OTHER = NAMESPACE.WORKFLOW + "operatingSystemOther"
  public static readonly BROWSER = NAMESPACE.WORKFLOW + "browser"
  public static readonly BROWSER_OTHER = NAMESPACE.WORKFLOW + "browserOther"
  public static readonly SEVERITY = NAMESPACE.WORKFLOW + "severity"
  public static readonly ERROR = NAMESPACE.WORKFLOW + "errorDetails"
  public static readonly REPRODUCE_STEPS = NAMESPACE.WORKFLOW + "reproduceSteps"
  public static readonly EXPECTED_RESULT = NAMESPACE.WORKFLOW + "expectedResult"
  public static readonly ACTUAL_RESULT = NAMESPACE.WORKFLOW + "actualResult"
  public static readonly RELATED_VERSION = NAMESPACE.WORKFLOW + "relatedVersion"
  public static readonly REQUESTED_ROLE = NAMESPACE.WORKFLOW + "requestedRole"
  public static readonly REQUESTED_NAMESPACE = NAMESPACE.WORKFLOW + "requestedNAMESPACE"
  public static readonly APPROVAL_TYPE = NAMESPACE.WORKFLOW + "approvalType"
  public static readonly HISTORY = NAMESPACE.WORKFLOW + "history"
  public static readonly HISTORY_PREDICATE = NAMESPACE.WORKFLOW + "historyPredicate"
  public static readonly HISTORY_ORIGINAL_OBJECT = NAMESPACE.WORKFLOW + "historyOriginalObject"
  public static readonly HISTORY_NEW_OBJECT = NAMESPACE.WORKFLOW + "historyNewObject"
  public static readonly HISTORY_CHANGE_DATE = NAMESPACE.WORKFLOW + "historyChangeDate"
  public static readonly MODIFIED_BY = NAMESPACE.WORKFLOW + "modifiedBy"
}
