// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {NAMESPACE} from "@/vocabulary/NAMESPACE";

export class XSD {

  public static readonly PREFIX = "xsd"
  public static readonly PATTERN = NAMESPACE.XSD + "pattern"
  public static readonly MIN_INCLUSIVE = NAMESPACE.XSD + "minInclusive"
  public static readonly MIN_EXCLUSIVE = NAMESPACE.XSD + "minExclusive"
  public static readonly MAX_INCLUSIVE = NAMESPACE.XSD + "maxInclusive"
  public static readonly MAX_EXCLUSIVE = NAMESPACE.XSD + "maxExclusive"
  public static readonly INTEGER = NAMESPACE.XSD + "integer"
  public static readonly STRING = NAMESPACE.XSD + "string"
  public static readonly BOOLEAN = NAMESPACE.XSD + "boolean"
  public static readonly LONG = NAMESPACE.XSD + "long"
  public static readonly DOUBLE = NAMESPACE.XSD + "double"
  public static readonly DATE_TIME = NAMESPACE.XSD + "dateTime"
  public static readonly NUMBER = NAMESPACE.XSD + "number"
  public static readonly DECIMAL = NAMESPACE.XSD + "decimal"
}
