export enum QUERY {
  DOMAIN = "http://endhealth.info/im#",
  IS_ALLOWABLE_RANGE = "http://endhealth.info/im#Query_IsAllowableRange",
  ALLOWABLE_RANGE_SUGGESTIONS = "http://endhealth.info/im#Query_AllowableRangeSuggestions",
  GET_SUBCLASSES = "http://endhealth.info/im#Query_GetSubClasses",
  GET_DESCENDANTS = "http://endhealth.info/im#Query_GetDescendants",
  IS_VALID_DESCENDANT = "http://endhealth.info/im#Query_IsValidDescendant",
  GET_ANCESTORS = "http://endhealth.info/im#Query_GetAncestors",
  SEARCH_CONTAINED_IN = "http://endhealth.info/im#Query_SearchContainedIn",
  ALLOWABLE_CHILD_TYPES = "http://endhealth.info/im#Query_AllowableChildTypes",
  PROPERTY_RANGE = "http://endhealth.info/im#Query_PropertyRange",
  OBJECT_PROPERTY_RANGE_SUGGESTIONS = "http://endhealth.info/im#Query_ObjectPropertyRangeSuggestions",
  DATA_PROPERTY_RANGE_SUGGESTIONS = "http://endhealth.info/im#Query_DataPropertyRangeSuggestions",
  ALLOWABLE_PROPERTIES = "http://endhealth.info/im#Query_AllowableProperties",
  ALLOWABLE_PROPERTY_ANCESTORS = "http://endhealth.info/im#Query_AllowablePropertyAncestors",
  IS_VALID_PROPERTY = "http://endhealth.info/im#Query_IsValidProperty",
  IS_VALID_TYPE = "http://endhealth.info/im#Query_IsValidType",
  ENTITY_FILTER = "http://endhealth.info/im#Query_EntityFilter",
  SEARCH_ENTITIES = "http://endhealth.info/im#Query_SearchEntities",
  SEARCH_FOLDERS = "http://endhealth.info/im#Query_SearchFolders",
  SEARCH_ALLOWABLE_CONTAINED_IN = "http://endhealth.info/im#Query_SearchAllowableContainedIn",
  SEARCH_MAIN_TYPES = "http://endhealth.info/im#Query_SearchmainTypes",
  DM_PROPERTY = "http://endhealth.info/im#Query_DataModelPropertyByShape",
  SEARCH_ALLOWABLE_SUBCLASS = "http://endhealth.info/im#Query_SearchAllowableSubclass",
  SEARCH_ALLOWABLE_CHILD_OF = "http://endhealth.info/im#Query_SearchAllowableChildOf",
  GET_VALUES_FROM_PROPERTY_RANGE = "http://endhealth.info/im#Query_GetValuesFromPropertyRange",
  GET_SUBSETS = "http://endhealth.info/im#Query_GetSubsets"
}
