enum Resource {
  ENTITY = "ENTITY",
  QUERY = "QUERY",
  USER = "USER",
  CONFIG = "CONFIG",
  TASK = "TASK",
  CODE_GEN = "CODE_GEN",
  FHIR = "FHIR",
  GITHUB = "GITHUB",
  POLICY = "POLICY",
  CASDOOR_USER = "CASDOOR_USER",
  DOCUMENT = "DOCUMENT",
  FOLDER = "FOLDER",
  DELTA = "DELTA",
  SET = "SET",
  BUG_REPORT = "BUG_REPOR",
  ROLE_REQUEST = "ROLE_REQUEST",
  GRAPH_REQUEST = "GRAPH_REQUEST",
  ENTITY_APPROVAL = "ENTITY_APPROVAL",
  QUERY_RESULTS = "QUERY_RESULTS",
  PAGE_ADMIN = "PAGE_ADMIN",
  PAGE_CREATOR = "PAGE_CREATOR",
  PAGE_EDITOR = "PAGE_EDITOR"
}

export default Resource;
