export enum TaskState {
  TODO = "TODO",
  IN_PROGRESS = "IN_PROGRESS",
  APPROVED = "APPROVED",
  COMPLETE = "COMPLETE",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  UNDER_REVIEW = "UNDER_REVIEW"
}
