export enum UserRole {
  ADMIN = "ADMIN",
  DEVELOPER = "DEVELOPER",
  PUBLISHER = "PUBLISHER",
  CREATOR = "CREATOR",
  EDITOR = "EDITOR",
  TASK_MANAGER = "TASK_MANAGER",
  AUTHORISER = "AUTHORISER",
  APPROVER = "APPROVER",
  EXECUTOR = "EXECUTOR",
  UPRN = "UPRN"
}
