import { Entail, IMQType, RuleAction } from "@/enums";
import { FunctionClause } from "@/interfaces/FunctionClause";
import { GroupBy } from "@/interfaces/GroupBy";
import { Having } from "@/interfaces/Having";
import { Node } from "@/interfaces/Node";
import { OrderLimit } from "@/interfaces/OrderLimit";
import { Path } from "@/interfaces/Path";
import { Prefix } from "@/interfaces/Prefix";
import { Return } from "@/interfaces/Return";
import { TTIriRef } from "@/interfaces/TTIriRef";
import { Where } from "@/interfaces/Where";
import { IriLD } from "@/interfaces/IriLD";

export interface Match extends IriLD{
  notExists?: boolean;
  ifTrue?: RuleAction;
  ifFalse?: RuleAction;
  nodeRef?: string;
  from?: string;
  typeOf?: Node;
  is?: Node;
  and?: Match[];
  or?: Match[];
  with?: Match[];
  union?: Match[];
  any?: Match[];
  where?: Where;
  then?: Match;
  graph?: Node;
  optional?: boolean;
  parameter?: string;
  function?: FunctionClause;
  entailment?: Entail;
  baseRule?: boolean;
  ruleNumber?: number;
  inverse?: boolean;
  activeOnly?: boolean;
  rule?: Match[];
  libraryItem?: string;
  invalid?: boolean;
  groupBy?: GroupBy[];
  orderBy?: OrderLimit;
  asDescription?: string;
  errorMessage?: string;
  draft?: boolean;
  having?: Having;
  description?: string;
  path?: Path[];
  node?: string;
  return?: Return[];
  prefixes?: Prefix[];
  columnGroup?: Match[];
  imMatch?: string;
  parentResult?: any;
  persistentIri?: TTIriRef;
  bindAs?: string;
  queryType?: IMQType;
  iri?: string;
  name?: string;
  as?: string;
}
