import { Argument } from "./Argument";
import { ArrayButtons } from "./ArrayButtons";
import { NodeShape } from "./NodeShape";
import { ParameterShape } from "./ParameterShape";
import { PropertyRange } from "./PropertyRange";
import { TTIriRef } from "./TTIriRef";

export interface PropertyShape {
  label?: string;
  comment?: string;
  name?: string;
  order: number;
  minCount?: number;
  maxCount?: number;
  componentType: TTIriRef;
  path: TTIriRef;
  datatype?: PropertyRange;
  node?: PropertyRange;
  validation?: TTIriRef;
  search?: TTIriRef;
  select?: TTIriRef[];
  argument?: Argument[];
  valueVariable?: string;
  isIri?: TTIriRef;
  isTextValue?: string;
  isNumericValue?: string;
  forceIsValue?: boolean;
  builderChild?: boolean;
  showTitle?: boolean;
  group?: TTIriRef;
  property?: PropertyShape[];
  clazz?: PropertyRange;
  validationErrorMessage?: string;
  function?: TTIriRef;
  parameter?: ParameterShape[];
  valueIri?: TTIriRef;
  expression?: NodeShape;
  arrayButtons?: ArrayButtons;
  hasValue?: any;
  hasValueType?: TTIriRef;
  definition?: string;
  ascending?: string;
  descending?: string;
  orderable?: boolean;
  hasValueSet?: TTIriRef;
  definingProperty?: boolean;
  isValidEntity?: TTIriRef;
  highCardinality?: boolean;
  isValidArguments?: Argument[];
  inversePath?: TTIriRef;
  generic?: boolean;
}
